CREATE PROCEDURE [dbo].[GetTaskRedirectionByAutomaticTaskId]
	@AutomaticTaskId nvarchar(100)
AS
	SELECT Id, AutomaticTaskId, WindowsAccount, OriginalEmployeeWindowsAccount, IsDeleted, RowVersion
	FROM [dbo].[AutogeneratedTaskRedirections]
RETURN 0
